// Generated by gencpp from file ros_basics_msgs/AddWaypoint.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_ADDWAYPOINT_H
#define ROS_BASICS_MSGS_MESSAGE_ADDWAYPOINT_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/AddWaypointRequest.h>
#include <ros_basics_msgs/AddWaypointResponse.h>


namespace ros_basics_msgs
{

struct AddWaypoint
{

typedef AddWaypointRequest Request;
typedef AddWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddWaypoint
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::AddWaypoint > {
  static const char* value()
  {
    return "d74cb68b87f4de16729735cf85932163";
  }

  static const char* value(const ::ros_basics_msgs::AddWaypoint&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::AddWaypoint > {
  static const char* value()
  {
    return "ros_basics_msgs/AddWaypoint";
  }

  static const char* value(const ::ros_basics_msgs::AddWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::AddWaypointRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::AddWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::AddWaypointRequest> should match
// service_traits::DataType< ::ros_basics_msgs::AddWaypoint >
template<>
struct DataType< ::ros_basics_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::AddWaypointResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::AddWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::AddWaypointResponse> should match
// service_traits::DataType< ::ros_basics_msgs::AddWaypoint >
template<>
struct DataType< ::ros_basics_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_ADDWAYPOINT_H
