// Generated by gencpp from file ros_basics_msgs/CurrentWaypoint.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_CURRENTWAYPOINT_H
#define ROS_BASICS_MSGS_MESSAGE_CURRENTWAYPOINT_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/CurrentWaypointRequest.h>
#include <ros_basics_msgs/CurrentWaypointResponse.h>


namespace ros_basics_msgs
{

struct CurrentWaypoint
{

typedef CurrentWaypointRequest Request;
typedef CurrentWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CurrentWaypoint
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::CurrentWaypoint > {
  static const char* value()
  {
    return "509ad6487577c30d7a7462175b53403c";
  }

  static const char* value(const ::ros_basics_msgs::CurrentWaypoint&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::CurrentWaypoint > {
  static const char* value()
  {
    return "ros_basics_msgs/CurrentWaypoint";
  }

  static const char* value(const ::ros_basics_msgs::CurrentWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::CurrentWaypointRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::CurrentWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::CurrentWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::CurrentWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::CurrentWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::CurrentWaypointRequest> should match
// service_traits::DataType< ::ros_basics_msgs::CurrentWaypoint >
template<>
struct DataType< ::ros_basics_msgs::CurrentWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::CurrentWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::CurrentWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::CurrentWaypointResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::CurrentWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::CurrentWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::CurrentWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::CurrentWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::CurrentWaypointResponse> should match
// service_traits::DataType< ::ros_basics_msgs::CurrentWaypoint >
template<>
struct DataType< ::ros_basics_msgs::CurrentWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::CurrentWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::CurrentWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_CURRENTWAYPOINT_H
