// Generated by gencpp from file ros_basics_msgs/RemoveWaypointResponse.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTRESPONSE_H
#define ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_msgs
{
template <class ContainerAllocator>
struct RemoveWaypointResponse_
{
  typedef RemoveWaypointResponse_<ContainerAllocator> Type;

  RemoveWaypointResponse_()
    : removed(false)  {
    }
  RemoveWaypointResponse_(const ContainerAllocator& _alloc)
    : removed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _removed_type;
  _removed_type removed;





  typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveWaypointResponse_

typedef ::ros_basics_msgs::RemoveWaypointResponse_<std::allocator<void> > RemoveWaypointResponse;

typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointResponse > RemoveWaypointResponsePtr;
typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointResponse const> RemoveWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.removed == rhs.removed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53d1c4b4c99c9164c7e77611a99d3fb3";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53d1c4b4c99c9164ULL;
  static const uint64_t static_value2 = 0xc7e77611a99d3fb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_msgs/RemoveWaypointResponse";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool removed\n"
;
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.removed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_msgs::RemoveWaypointResponse_<ContainerAllocator>& v)
  {
    s << indent << "removed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.removed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTRESPONSE_H
