// Generated by gencpp from file ros_basics_msgs/RemoveWaypointRequest.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTREQUEST_H
#define ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_msgs
{
template <class ContainerAllocator>
struct RemoveWaypointRequest_
{
  typedef RemoveWaypointRequest_<ContainerAllocator> Type;

  RemoveWaypointRequest_()
    : idx(0)  {
    }
  RemoveWaypointRequest_(const ContainerAllocator& _alloc)
    : idx(0)  {
  (void)_alloc;
    }



   typedef uint32_t _idx_type;
  _idx_type idx;





  typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveWaypointRequest_

typedef ::ros_basics_msgs::RemoveWaypointRequest_<std::allocator<void> > RemoveWaypointRequest;

typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointRequest > RemoveWaypointRequestPtr;
typedef boost::shared_ptr< ::ros_basics_msgs::RemoveWaypointRequest const> RemoveWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5322f435d05c56c40d0c329084ca3cb8";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5322f435d05c56c4ULL;
  static const uint64_t static_value2 = 0x0d0c329084ca3cb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_msgs/RemoveWaypointRequest";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 idx\n"
;
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_msgs::RemoveWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINTREQUEST_H
