// Generated by gencpp from file ros_basics_msgs/SetWaypoints.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTS_H
#define ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTS_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/SetWaypointsRequest.h>
#include <ros_basics_msgs/SetWaypointsResponse.h>


namespace ros_basics_msgs
{

struct SetWaypoints
{

typedef SetWaypointsRequest Request;
typedef SetWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWaypoints
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::SetWaypoints > {
  static const char* value()
  {
    return "0b9e83915d91f5a57f9839688cdeccfb";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypoints&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::SetWaypoints > {
  static const char* value()
  {
    return "ros_basics_msgs/SetWaypoints";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::SetWaypointsRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::SetWaypoints >
template<>
struct MD5Sum< ::ros_basics_msgs::SetWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::SetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::SetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::SetWaypointsRequest> should match
// service_traits::DataType< ::ros_basics_msgs::SetWaypoints >
template<>
struct DataType< ::ros_basics_msgs::SetWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::SetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::SetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::SetWaypointsResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::SetWaypoints >
template<>
struct MD5Sum< ::ros_basics_msgs::SetWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::SetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::SetWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::SetWaypointsResponse> should match
// service_traits::DataType< ::ros_basics_msgs::SetWaypoints >
template<>
struct DataType< ::ros_basics_msgs::SetWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::SetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::SetWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTS_H
