// Generated by gencpp from file ros_basics_msgs/SimplePoseStamped.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_SIMPLEPOSESTAMPED_H
#define ROS_BASICS_MSGS_MESSAGE_SIMPLEPOSESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_basics_msgs/SimplePose.h>

namespace ros_basics_msgs
{
template <class ContainerAllocator>
struct SimplePoseStamped_
{
  typedef SimplePoseStamped_<ContainerAllocator> Type;

  SimplePoseStamped_()
    : header()
    , pose()  {
    }
  SimplePoseStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ros_basics_msgs::SimplePose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> const> ConstPtr;

}; // struct SimplePoseStamped_

typedef ::ros_basics_msgs::SimplePoseStamped_<std::allocator<void> > SimplePoseStamped;

typedef boost::shared_ptr< ::ros_basics_msgs::SimplePoseStamped > SimplePoseStampedPtr;
typedef boost::shared_ptr< ::ros_basics_msgs::SimplePoseStamped const> SimplePoseStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b32f339a300d57b131bcc5fa4fb7c1d";
  }

  static const char* value(const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b32f339a300d57bULL;
  static const uint64_t static_value2 = 0x131bcc5fa4fb7c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_msgs/SimplePoseStamped";
  }

  static const char* value(const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ros_basics_msgs/SimplePose pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_basics_msgs/SimplePose\n"
"geometry_msgs/Point xyz\n"
"ros_basics_msgs/RPY rpy\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: ros_basics_msgs/RPY\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimplePoseStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_msgs::SimplePoseStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::ros_basics_msgs::SimplePose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_SIMPLEPOSESTAMPED_H
