// Generated by gencpp from file ros_basics_msgs/CheckWaypointReached.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_CHECKWAYPOINTREACHED_H
#define ROS_BASICS_MSGS_MESSAGE_CHECKWAYPOINTREACHED_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/CheckWaypointReachedRequest.h>
#include <ros_basics_msgs/CheckWaypointReachedResponse.h>


namespace ros_basics_msgs
{

struct CheckWaypointReached
{

typedef CheckWaypointReachedRequest Request;
typedef CheckWaypointReachedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckWaypointReached
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::CheckWaypointReached > {
  static const char* value()
  {
    return "04f34cae25ac370b7cb9f4cd6bf31ca3";
  }

  static const char* value(const ::ros_basics_msgs::CheckWaypointReached&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::CheckWaypointReached > {
  static const char* value()
  {
    return "ros_basics_msgs/CheckWaypointReached";
  }

  static const char* value(const ::ros_basics_msgs::CheckWaypointReached&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::CheckWaypointReachedRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::CheckWaypointReached >
template<>
struct MD5Sum< ::ros_basics_msgs::CheckWaypointReachedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::CheckWaypointReached >::value();
  }
  static const char* value(const ::ros_basics_msgs::CheckWaypointReachedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::CheckWaypointReachedRequest> should match
// service_traits::DataType< ::ros_basics_msgs::CheckWaypointReached >
template<>
struct DataType< ::ros_basics_msgs::CheckWaypointReachedRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::CheckWaypointReached >::value();
  }
  static const char* value(const ::ros_basics_msgs::CheckWaypointReachedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::CheckWaypointReachedResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::CheckWaypointReached >
template<>
struct MD5Sum< ::ros_basics_msgs::CheckWaypointReachedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::CheckWaypointReached >::value();
  }
  static const char* value(const ::ros_basics_msgs::CheckWaypointReachedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::CheckWaypointReachedResponse> should match
// service_traits::DataType< ::ros_basics_msgs::CheckWaypointReached >
template<>
struct DataType< ::ros_basics_msgs::CheckWaypointReachedResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::CheckWaypointReached >::value();
  }
  static const char* value(const ::ros_basics_msgs::CheckWaypointReachedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_CHECKWAYPOINTREACHED_H
