// Generated by gencpp from file ros_basics_msgs/GetWaypoints.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_GETWAYPOINTS_H
#define ROS_BASICS_MSGS_MESSAGE_GETWAYPOINTS_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/GetWaypointsRequest.h>
#include <ros_basics_msgs/GetWaypointsResponse.h>


namespace ros_basics_msgs
{

struct GetWaypoints
{

typedef GetWaypointsRequest Request;
typedef GetWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypoints
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::GetWaypoints > {
  static const char* value()
  {
    return "0b9e83915d91f5a57f9839688cdeccfb";
  }

  static const char* value(const ::ros_basics_msgs::GetWaypoints&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::GetWaypoints > {
  static const char* value()
  {
    return "ros_basics_msgs/GetWaypoints";
  }

  static const char* value(const ::ros_basics_msgs::GetWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::GetWaypointsRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::GetWaypoints >
template<>
struct MD5Sum< ::ros_basics_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::GetWaypointsRequest> should match
// service_traits::DataType< ::ros_basics_msgs::GetWaypoints >
template<>
struct DataType< ::ros_basics_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::GetWaypointsResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::GetWaypoints >
template<>
struct MD5Sum< ::ros_basics_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::GetWaypointsResponse> should match
// service_traits::DataType< ::ros_basics_msgs::GetWaypoints >
template<>
struct DataType< ::ros_basics_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_basics_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_GETWAYPOINTS_H
