// Generated by gencpp from file ros_basics_msgs/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINT_H
#define ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <ros_basics_msgs/RemoveWaypointRequest.h>
#include <ros_basics_msgs/RemoveWaypointResponse.h>


namespace ros_basics_msgs
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace ros_basics_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "034564533f8553dbc4b5af50cf500e64";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::ros_basics_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "ros_basics_msgs/RemoveWaypoint";
  }

  static const char* value(const ::ros_basics_msgs::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_msgs::RemoveWaypointRequest> should match
// service_traits::MD5Sum< ::ros_basics_msgs::RemoveWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::RemoveWaypointRequest> should match
// service_traits::DataType< ::ros_basics_msgs::RemoveWaypoint >
template<>
struct DataType< ::ros_basics_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_msgs::RemoveWaypointResponse> should match
// service_traits::MD5Sum< ::ros_basics_msgs::RemoveWaypoint >
template<>
struct MD5Sum< ::ros_basics_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_msgs::RemoveWaypointResponse> should match
// service_traits::DataType< ::ros_basics_msgs::RemoveWaypoint >
template<>
struct DataType< ::ros_basics_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::ros_basics_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_REMOVEWAYPOINT_H
