// Generated by gencpp from file ros_basics_msgs/SetWaypointsRequest.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSREQUEST_H
#define ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace ros_basics_msgs
{
template <class ContainerAllocator>
struct SetWaypointsRequest_
{
  typedef SetWaypointsRequest_<ContainerAllocator> Type;

  SetWaypointsRequest_()
    : waypoints()  {
    }
  SetWaypointsRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointsRequest_

typedef ::ros_basics_msgs::SetWaypointsRequest_<std::allocator<void> > SetWaypointsRequest;

typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsRequest > SetWaypointsRequestPtr;
typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsRequest const> SetWaypointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator1> & lhs, const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b9e83915d91f5a57f9839688cdeccfb";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b9e83915d91f5a5ULL;
  static const uint64_t static_value2 = 0x7f9839688cdeccfbULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_msgs/SetWaypointsRequest";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_msgs::SetWaypointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSREQUEST_H
