// Generated by gencpp from file ros_basics_msgs/SetWaypointsResponse.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSRESPONSE_H
#define ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_msgs
{
template <class ContainerAllocator>
struct SetWaypointsResponse_
{
  typedef SetWaypointsResponse_<ContainerAllocator> Type;

  SetWaypointsResponse_()
    {
    }
  SetWaypointsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointsResponse_

typedef ::ros_basics_msgs::SetWaypointsResponse_<std::allocator<void> > SetWaypointsResponse;

typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsResponse > SetWaypointsResponsePtr;
typedef boost::shared_ptr< ::ros_basics_msgs::SetWaypointsResponse const> SetWaypointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ros_basics_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_msgs/SetWaypointsResponse";
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_basics_msgs::SetWaypointsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_MSGS_MESSAGE_SETWAYPOINTSRESPONSE_H
